name: feedback_ideas_app_flutter
description: A new Flutter project with Serverpod.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  serverpod_flutter: 2.0.2
  serverpod_auth_shared_flutter: 2.0.2
  google_fonts: ^6.2.1
  shadcn_ui: ^0.7.3
  go_router: ^14.2.1
  crypto: ^3.0.3
  url_strategy: ^0.2.0
  email_validator: ^3.0.0
  feedback_ideas_app_client:
    path: ../feedback_ideas_app_client


  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_lints: '>=3.0.0 <5.0.0'
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo.png
